# kumolocal.ini - Local IP address configuration for kumolocal zones.
# Zone names must match the zone names configured in the Kumo Cloud app.

[Main Level]
ip_address = 192.168.86.84

[Kitchen]
ip_address = 192.168.86.24

[Basement]
ip_address = 192.168.86.47
